### ISSUE TITLE
Popup truncated if too close to the border of the window

### ISSUE THREAD

**Issue by antilogos** [meta-is-beta/horadric-helper#23] opened 2021-12-21 16:54 UTC
When a lot of elements are displayed on one line, or just too close to the left/right border of the windows, the popup windows are still centered around their anchor div, causing cut in the popup display.
Would it be possible to detect if the popup is not displayed properly and have it changes position?

html sample file:
[test.txt](https://github.com/meta-is-beta/horadric-helper/files/7756840/test.txt)
or live example:
https://sites.google.com/view/poefr/objets/objet-unique/uniques-de-boss#h.3zzi2t9pfyf8

**Comment by meta-is-beta** [comment] 2022-02-26 19:15
Sorry for long silence, but I was away due to COVID. 
Did you mean this?

![image](https://user-images.githubusercontent.com/82339211/155855499-088ac70f-ae8f-4bb5-8444-b2db70098210.png)

The reason why popups get cut-off is because you are using nested iframes. Library can only determine if something is visible within it's own scope, it will not be able to adjust to anything outside of that - so it has no idea about page outside of it's own iframe.

Also your iframe has `overflow: hidden;` and `width: 100%`. This will cause popups to get wonky because you are manipulating internal viewport of iframe from outside, so anything inside is not aware of it and can't adjust.

You are currently using 3 levels of nested iframes - best solution would be to get rid of them all. But if that's not possible then you could try to set constant dimensions of the content inside of them instead of using `width: 100%` and `height: 100%`.


PS.
The reason why library can't adjust to content outside of it's iframe is not because of any issues with library itself - this is caused by browsers blocking upward access from iframes due to security reasons. There is sadly nothing I could change in the code that would fix this, this is just how iframes work.

**Comment by antilogos** [comment] 2022-02-28 15:05
I have provided a txt file that can be read as html, that just the main code, without any iframe, and the first item goes out of the screen.
![image](https://user-images.githubusercontent.com/16670931/156005342-096d111f-1526-4313-a732-406bbb43ade5.png)
I think the `transform: translate3d(-511px, 256px, 0px);` added to one of the popup element should not be able to have x-translation lower than the x position of it's parent element, if that is possible.
EDIT: I'll be using `as-showcase` for now, since integrating in google site is my final target, and I'm limited by how google site can integrate html code

**Comment by meta-is-beta** [comment] 2022-03-04 08:41
I can see now - there is some weirdness, especially in smaller resolutions. Right now I can't really change positioning behavior, because it's handled by external library - `popper.js`. But I will try to upgrade it to the newest version - it might help.

**Comment by meta-is-beta** [comment] 2022-03-05 16:41
Ok, so this is a bug in Popper.js. In some resolution it just goes crazy and position elements way to much to the left. I event know how to fix it and I would submit a PR, but creator of the library decided to remove it's repository completely.... 
So in short - I can't fix it, but I can replace Popper with something else. But to do that I need to upgrade entire project from Vue2 to Vue3. So that will take a while, possibly few months.

**Comment by meta-is-beta** [comment] 2022-04-08 21:43
Fixed as of version 0.12

**Closed as completed** 2022-04-08 21:42 UTC
